sudo: required

language: ruby

services:
  - docker

before_install:
- docker pull ubuntu:16.04

script:
  - sudo docker run -it -v `pwd`/../ZEGBot:/ZEGBot ubuntu:16.04 /bin/sh -c "cd /ZEGBot; sh build.sh"
